---
# The network cidr and service cidr are set in the ovn-config configmap
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-config
  namespace: openshift-ovn-kubernetes
data:
  net_cidr:   {{.OVN_cidr}}
  svc_cidr:   {{.OVN_service_cidr}}
  k8s_apiserver: "{{.K8S_APISERVER}}"
---
# The ovn-kube leader election is based on the ovn-kubernetes-master configmap
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-kubernetes-master
  namespace: openshift-ovn-kubernetes

